version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: comments-app-backend
    restart: always
    expose:
      - 3000
    env_file:
      - .env
    volumes:
      - ./uploads:/usr/src/app/uploads 
    command: ["sh", "-c", "npx prisma migrate deploy && npx prisma generate && npm start"]
    depends_on:
      - db
  db:
    image: postgres:13
    container_name: postgres-db
    env_file:
      - .env
    expose:
      - 5432
    restart: always
    volumes:
      - ./pg_data:/var/lib/postgresql/data
  nginx:
    image: nginx:latest
    container_name: my-nginx
    ports:
      - "5000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
